### ISSUE TITLE
Change sort order

### ISSUE THREAD

**Issue by vistar** [flyingrhinonz/nccm#10]
from alpabetical to in order of adding to config file

**Comment by flyingrhinonz** [comment]
nccm was designed as a filtering tool in which ordering is secondary to ease of narrowing down your selection through filtering. 
Even if I  did add an option to disable the initial sorting, there's no mechanism in place to restore the load order after manual sorting occurred so it's going to be a one way trip and incomplete solution.

If you want this you can edit your copy of the code and remove the sort function that's done after the list is loaded.
But you'll encounter the same limit I mentioned above.
