### ISSUE TITLE
NCCM prompts before connecting

### ISSUE THREAD

**Issue by MischaBoender** [flyingrhinonz/nccm#12]
Installed a new NCCM instance this weekend, used the default YAML and added my connection info and set _nccm_loop_nccm_ to _true_.

When I connect to one of my servers I get:
`Press Enter to continue (before connecting) ...`
which is unexpected. The same when exiting the SSH connection:
`Press Enter to continue (before returning to nccm) ...`

Relevant setting from the YAML:
`nccm_config_promptuser: false`

**Comment by nf9k** [comment]
I am seeing the same on 1.6.20.

From my nccm.yml:

`nccm_config_promptuser: false`

I am not using the looping option, so it exits.

Running debug I found the following:

`Dec 06 19:58:49 linux-macbook-air nccm[21498]: <DEBUG> (2021-12-06 19:58:49.764 , PN: MainProcess , MN: nccm , FN: Load , LI: 1105 , TN: MainThread):    Loaded nccm.yml config item:  GlobalConfig.PromptToContinue == False
Dec 06 19:58:49 linux-macbook-air nccm[21498]: <DEBUG> (2021-12-06 19:58:49.808 , PN: MainProcess , MN: nccm , FN: LogGlobalConfig , LI: 1735 , TN: MainThread):        ....GlobalConfig.PromptToContinue == False`

Which seems to indicate that the config item was read in with the expected value.

**Comment by flyingrhinonz** [comment]
Thanks guys.
Fixed in new commit.

Ken.

**Comment by MischaBoender** [comment]
I can confirm the issues was fixed, thanks!
