### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Mte90** [flyingrhinonz/nccm#13]
Downloaded and at first run I get this.
```
Traceback (most recent call last):
  File "/nccm/nccm", line 2724, in <module>
    main()
  File "/nccm/nccm", line 2605, in main
    CommandInfo = curses.wrapper(MainCursesFunction)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/nccm/nccm", line 2176, in MainCursesFunction
    ConnectionsList, ConnBox, FilterBox, CyclicTextboxObjects = SetupWindows(stdscr)
  File "/nccm/nccm", line 2142, in SetupWindows
    ConnectionsList.Load()
  File "/nccm/nccm", line 1111, in Load
    with open (FileLooper, 'r') as ConfigFileToRead:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/nccm.yml'
```

**Comment by flyingrhinonz** [comment]
Did you copy the nccm.yml file per the install instructions?

The ssh connections/config file nccm.yml should be copied to any one of the following locations, and is loaded from the first location found in the following order:

~/.config/nccm/nccm.yml
~/.nccm.yml
~/nccm.yml
/etc/nccm.yml


If you still have trouble - follow this from the troubleshooting section:

Increase logging verbosity level to debug using the -d or --debug command line arguments. This is by far the easiest way to debug and covers most scenarios except for faults that occur before the code actually reads the -d command line argument. Tip - to extract recent logs from the system use: journalctl -t "nccm" --since -10min >> /tmp/nccm.log

**Comment by Mte90** [comment]
No I just cloned the repo and tried to execute it, maybe in this cases should alert the user without a crash like this.
As per in that case the nccm.yml is in the same folder of the tool.

Before to use it I wanted to try it and see how works before starting to put the config file in one of those folders.

**Comment by flyingrhinonz** [comment]
Good idea to alert the user, I'll add this feature.

No problem to load nccm.yml from the same folder as the tool but it breaks tradition of config files in expected locations (complicates doing backups,etc). Let's leave this idea open and see what feedback other users give. Personally I prefer not to add this.

**Comment by Mte90** [comment]
Me too but in my case was just a testing so probably as fallback in case the config file is not found can try in this way and otherwise show an error about config file not found.

**Comment by flyingrhinonz** [comment]
I'll add a user friendly note about file not found instead of the exception.

**Comment by flyingrhinonz** [comment]
I've improved this and will test for a couple days before pushing the update.
Here's what it looks like now:

Error loading:  nccm.yml  from any of the following paths:
['/home/ken/.config/nccm/nccm.yml', '/home/ken/.nccm.yml', '/home/ken/nccm.yml', '/etc/nccm.yml']

Tip: check if file exists in one of these locations, permissions, selinux context, etc.

Reraising exception for further debugging info and to initiate screen restore...


Traceback (most recent call last):
  File "/usr/local/bin/cm", line 2738, in <module>
    main()
  File "/usr/local/bin/cm", line 2619, in main
    CommandInfo = curses.wrapper(MainCursesFunction)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/bin/cm", line 2190, in MainCursesFunction
    ConnectionsList, ConnBox, FilterBox, CyclicTextboxObjects = SetupWindows(stdscr)
  File "/usr/local/bin/cm", line 2156, in SetupWindows
    ConnectionsList.Load()
  File "/usr/local/bin/cm", line 1125, in Load
    raise Exc
  File "/usr/local/bin/cm", line 1111, in Load
    with open (FileLooper, 'r') as ConfigFileToRead:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/nccm.yml'

**Comment by flyingrhinonz** [comment]
Fixed.
