### ISSUE TITLE
Do not add "-p 22" if port is unspecified

### ISSUE THREAD

**Issue by basilgohar** [flyingrhinonz/nccm#19]
If I leave the port unspecified for a connection, `-p 22` is manually inserted, but this is redundant and also overrides any value that I already have configured in the global system ssh_config file.   It would be better to not force a value to be inserted so that, if left unset, the default that was configured elsewhere could be used.  This is useful for when you have different services connecting via SSH (e.g., scripts) that may not use nccm but I want to also be able to use nccm.

**Comment by flyingrhinonz** [comment]
That's a good suggestion. I will probably add this as a config item rather than forcing a new type of behavior. This will cover all cases.

**Comment by flyingrhinonz** [comment]
Try out new nccm from test branch.
If it's stable for a couple weeks I will merge it into master.

**Comment by flyingrhinonz** [comment]
merged into master.
