### ISSUE TITLE
Ability to pass config file as parameter

### ISSUE THREAD

**Issue by DavidPavlicek** [flyingrhinonz/nccm#20]
A user should be able to explicitly pass a config file path as a command-line argument.

**Comment by flyingrhinonz** [comment]
This is pushing nccm more towards regular ssh than its intended goal of being a preconfigured interactive tool.
Leaving this open for now , let's see what feedback other users have.

**Comment by flyingrhinonz** [comment]
Leaving it as is for now. No other users support this request.
