### ISSUE TITLE
_curses.error: endwin() returned ERR

### ISSUE THREAD

**Issue by Mte90** [flyingrhinonz/nccm#22]
After selecting the server I am getting this error:
```
Traceback (most recent call last):
  File "/home/mte90/Desktop/kde/nccm/nccm/nccm", line 2862, in <module>
    main()
  File "/home/mte90/Desktop/kde/nccm/nccm/nccm", line 2743, in main
    CommandInfo = curses.wrapper(MainCursesFunction)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/curses/__init__.py", line 101, in wrapper
    endwin()
_curses.error: endwin() returned ERR
```

I don't see a requirements.txt orr pyproject.toml so I can't check the dependencies I need or the version I have is compatible.

**Comment by HekkiMelody** [comment]
I have this same issue since a few days, on debian testing.

**Comment by Mte90** [comment]
If this can be helpful these are the last errors in `journalctl`:

```
dic 06 16:23:23 KITT nccm[98608]: <DEBUG> (2023-12-06 16:23:23.738 , PN: MainProcess , MN: nccm , FN: LogPositions , LI: 1848 , TN: MainThread):    Comment == Enter key , self.Name = ConnectionsList , self.YOff>
dic 06 16:23:23 KITT nccm[98608]: <DEBUG> (2023-12-06 16:23:23.738 , PN: MainProcess , MN: nccm , FN: GetCommandLine , LI: 1656 , TN: MainThread):    SelectedEntry = <__main__.ServerXS object at 0x7f781a8d9690>
dic 06 16:23:23 KITT nccm[98608]: <DEBUG> (2023-12-06 16:23:23.738 , PN: MainProcess , MN: nccm , FN: GetCommandLine , LI: 1713 , TN: MainThread):    ServerXSNum (this is the connection list line number) == 0 ,>
lines 19198
```

**Comment by HekkiMelody** [comment]
I'm trying to investigate more, for now what I can say is that evidence points to Ncurses patch 20231121 breaking NCCM

https://invisible-island.net/ncurses/NEWS.html#index-t20231121

NCCM broke when I updated ncurses-related packages from `6.4+20231016-1` to `6.4+20231121-1` (in debian's versioning system) so the breaking patch must be one of those in there, at least.

**Comment by HekkiMelody** [comment]
I can confirm that, at least as a stopgap measure, downgrading ncurses work

on Debian, for example:

`sudo apt install libncurses6=6.4-4 libncursesw6=6.4-4 libtinfo6=6.4-4 ncurses-bin=6.4-4`

**Comment by HekkiMelody** [comment]
I've found the problem and suggested a fix here: https://github.com/flyingrhinonz/nccm/pull/24

Would appreciate if you could test it!
