### ISSUE TITLE
nccm doesn't start

### ISSUE THREAD

**Issue by napitek** [flyingrhinonz/nccm#3]
nccm cloned from git.
copied to /usr/local/bin folder, permissions assigned and config file controlled with yamllint.
when I launch it...

`Traceback (most recent call last):
  File "/usr/local/bin/nccm", line 1522, in <module>
    main()
  File "/usr/local/bin/nccm", line 1502, in main
    CommandLine = curses.wrapper(MainCursesFunction)
  File "/usr/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/bin/nccm", line 1201, in MainCursesFunction
    ConnectionsList, ConnBox, FilterBox, CyclicTextboxObjects = SetupWindows(stdscr)
  File "/usr/local/bin/nccm", line 1170, in SetupWindows
    ConnectionsList.Load()
  File "/usr/local/bin/nccm", line 818, in Load
    raise Exc
  File "/usr/local/bin/nccm", line 771, in Load
    FSL.UserName = self.LoadedServersDict[FriendlyName].get(
TypeError: get expected at most 2 arguments, got 3`

**Comment by flyingrhinonz** [comment]
You're right, there's a bug.
Let me fix and update.

**Comment by flyingrhinonz** [comment]
Fixed and uploaded.
Thanks for the bug report.

**Comment by gitscosh** [comment]
I just cloned this today because I want to use it on my MBP (running fish shell, python 3.9) and I'm getting this same error. Any ideas?

**Comment by flyingrhinonz** [comment]
Thanks for reporting this bug.
I'll check it this week.

**Comment by flyingrhinonz** [comment]
Works for me.
Follow the troubleshooting instructions - enable debugging, check the log - it will give an idea what's wrong.
If you're still stuck send the debug level syslog and we'll check.

**Comment by gitscosh** [comment]
Turns out my config file was outdated. I pulled the latest template from your repo and it starts up now.
