### ISSUE TITLE
Error when disconnecting in Ubuntu WSL (Windows 10 1809)

### ISSUE THREAD

**Issue by riccalioliojr** [flyingrhinonz/nccm#4]
When I disconnect an SSH session, I get this error message:

```
***** SSH FAILED! Exit code = 1 *****

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/bin/nccm", line 1636, in main
    subprocess.run(CommandLine, check=True)          # Connect to the ssh server
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh', 'username@fqdn', '-o', 'ServerAliveInterval=30']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/bin/nccm", line 1653, in <module>
    main()
  File "/usr/local/bin/nccm", line 1649, in main
    LogWrite.warning('ssh failed. Exit code = {}'.format(CPE.returncode))
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/local/bin/nccm", line 528, in emit
    super(CustomHandler, self).emit(record)
Message: 'ssh failed. Exit code = 1'
Arguments: ()
```

**Comment by flyingrhinonz** [comment]
It looks like ssh returned exit code != 0 pointing to something that made ssh unhappy which passed it on to nccm.
I'll try to reproduce it here and improve ssh != 0 exit code handling.

Thanks for the bug report.

**Comment by flyingrhinonz** [comment]
Logging improved. Can you please try again:

- Upgrade nccm to the latest version
- Start it with: nccm -d
- Reproduce the error
- Send me the log lines from /var/log/syslog

Thanks.

**Comment by riccalioliojr** [comment]
I'm using `nccm` in WSL1 and it seems I cannot run `rsyslog` in here...

```
user@COMPUTERNAME:~$ sudo systemctl start rsyslog.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

**Comment by flyingrhinonz** [comment]
I've never tested it under any non-native-linux platform so I don't know if/how it works.
Sorry but I can't really help here, because I have no access to WSL neither have I got experience with WSL.
Perhaps one of the other users can help? If someone can suggest a solution I will fix and  implement the solution in the next build.

You're talking about logging though, does the latest version of nccm still crash in regular ssh connection?

**Comment by riccalioliojr** [comment]
Actually, the version I cloned from 4 days ago does not crash that often. I often have multiple SSH connections and disconnections to different machines throughout the day and I think it only crashed less than 5 times. Previous version crashed almost every time, which, by the way, only started crashing after I performed an `apt upgrade` of all packages after the new year. It did not happen before that.

**Comment by flyingrhinonz** [comment]
This is strange because nccm should not crash - I am capturing ssh errors and replacing it with my own error message and exiting nicely.
Can you send me terminal output next time it crashes? Perhaps I've missed a check somewhere.
If you can get the syslog also that will be great, but terminal log is useful.

Thanks.

**Comment by riccalioliojr** [comment]
I'll let you know. It doesn't seem to be happening anymore but I'll observe it until Monday EOB.

**Comment by riccalioliojr** [comment]
First error for today (terminal output):

```
***** SSH FAILED! Exit code = 255 *****

--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/bin/nccm", line 1653, in main
    subprocess.run(CommandLine, check=True)          # Connect to the ssh server
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh', 'user@fqdn', '-o', 'ServerAliveInterval=30']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/bin/nccm", line 1671, in <module>
    main()
  File "/usr/local/bin/nccm", line 1666, in main
    LogWrite.warning('ssh failed. Exit code = {}'.format(CPE.returncode))
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/local/bin/nccm", line 536, in emit
    super(CustomHandler, self).emit(record)
Message: 'ssh failed. Exit code = 255'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/local/bin/nccm", line 1653, in main
    subprocess.run(CommandLine, check=True)          # Connect to the ssh server
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ssh', 'user@fqdn', '-o', 'ServerAliveInterval=30']' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/bin/nccm", line 1671, in <module>
    main()
  File "/usr/local/bin/nccm", line 1667, in main
    LogWrite.warning('Further debug details: {}'.format(CPE))
  File "/usr/lib/python3.8/logging/__init__.py", line 1446, in warning
    self._log(WARNING, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1577, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1587, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1649, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 950, in handle
    self.emit(record)
  File "/usr/local/bin/nccm", line 536, in emit
    super(CustomHandler, self).emit(record)
Message: "Further debug details: Command '['ssh', 'user@fqdn', '-o', 'ServerAliveInterval=30']' returned non-zero exit status 255."
Arguments: ()
```

**Comment by riccalioliojr** [comment]
Not sure if this is relevant but here's another info: My `nccm.yml` file is a soft link to a file located in the `C:` drive which is represented as a mounted drive in `WSL`.

`nccm.yml -> /mnt/c/my-files/nccm.yml*`

**Comment by flyingrhinonz** [comment]
Thanks. Let me look into this.  I want to investigate why the crash didn't get captured by my code.

**Comment by shd2h** [comment]
I don't particularly have anything to add about the ssh disconnect (other than I've also experienced it intermittently when using nccm under WSL2 as well); but I think the reason the ssh exception handling isn't working is because WSL syslog doesn't always seem to work OOTB, and there isn't always a /dev/log file for the script to log to because of this. The below outputs are all from the WSL1 Debian version:

```
sysadmin@Elsenova:~$ ls -lh /dev/log
ls: cannot access '/dev/log': No such file or directory
```

as noted earlier in this issue, systemd commands don't work because WSL, but service does:

```
root@Elsenova:~# service rsyslog start
[ ok ] Starting enhanced syslogd: rsyslogd.
root@Elsenova:~# service rsyslog status
[ ok ] rsyslogd is running.
root@Elsenova:~# ls -lh /dev/log
srw-rw-rw- 1 root root 0 Jan 22 11:40 /dev/log
```

When googling around, I've seen some reports that say you may need to reinstall rsyslog before it will start successfully, so bear that in mind (https://gist.github.com/0x49D1/596d457921034e9c18e5e1052a4ad515):
`sudo apt install --reinstall rsyslog`

The above all said, even once it's started, syslog apparently doesn't function properly under WSL1: https://github.com/Microsoft/WSL/issues/534
So, I don't know whether the logging under WSL1 will work well enough to capture the ssh error.

**Comment by riccalioliojr** [comment]
@shd2h I tried reinstalling `rsyslog` as you mentioned but the service still fails to start with the same error message: `System has not been booted with systemd as init system (PID 1). Can't operate.`

**Comment by shd2h** [comment]
Hmmm, I'm honestly not sure then - I do get the same "System has not been booted with systemd" error as you do when trying to execute `systemctl` commands, but not with `service`.
I checked in Ubuntu WSL both on my PC running Win 10 2004, and in a VM running 1809, but both worked well for me, so I don't think it's a Windows or WSL version problem.
I've included the complete sequence of commands I ran in a fresh Ubuntu WSL install to get rsyslogd to start in case that helps at all:

```
root@DESKTOP-SUCQBGA:~# systemctl start rsyslog.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
root@DESKTOP-SUCQBGA:~# service rsyslog status
 * rsyslogd is not running
root@DESKTOP-SUCQBGA:~# service rsyslog start
 * Starting enhanced syslogd rsyslogd                                                                                   
rsyslogd: set SO_TIMESTAMP failed on '/dev/log': Invalid argument [v8.2001.0]
rsyslogd: imklog: cannot open kernel log (/proc/kmsg): No such file or directory.
rsyslogd: activation of module imklog failed [v8.2001.0 try https://www.rsyslog.com/e/2145 ]
                                                                                                                 [ OK ]
root@DESKTOP-SUCQBGA:~# service rsyslog status
 * rsyslogd is running
root@DESKTOP-SUCQBGA:~# ls -lh /dev/log
srw-rw-rw- 1 root root 0 Jan 22 17:33 /dev/log
root@DESKTOP-SUCQBGA:~#
```

**Comment by flyingrhinonz** [comment]
Try this  - in your nccm.yml file - change the log level to:  critical   .
Because I don't have any "critical" level calls this should never write anything to syslog and therefore never fail on syslog exception.

This will prove it's only the underlying syslog that's causing problems and there's no bug in nccm.

Thanks.

**Comment by flyingrhinonz** [comment]
I've added an option in the code to completely disable logging. Check the README for instructions.
I prefer that you fix your syslog (because it's useful for you in many other ways), but now you've got two options in NCCM to bypass syslog.

**Comment by riccalioliojr** [comment]
@shd2h - Yes, it also works for me when I use the `service` command. Thanks!

@flyingrhinonz - I will try the first option, `nccm_config_loglevel: critical`, starting today. I'll let you know. Thanks!

**Comment by riccalioliojr** [comment]
First error message I encounter today after disconnecting:

```sh
Connection to fqdn closed.

***** SSH FAILED! Exit code = 2 *****
```

**Comment by flyingrhinonz** [comment]
Well this proves that the python dumps were coming from the syslog calls and not a bug in nccm. At least we've got one issue sorted.

Now let's try to figure out why ssh is failing under nccm....

Can you use regular ssh for a while (without nccm) and immediately after you disconnect type:  echo $?
Or in one command, similar to this:  **ssh admin@192.168.246.1; echo $?**

If you see non zero exit code from command line ssh - then the problem is coming from ssh and nccm is simply reading the exit code and responding.

Thanks.

**Comment by flyingrhinonz** [comment]
Are you rebooting your server inside ssh/nccm or is ssh disconnecting in other ways that 'exit' ?
Both these cause non-zero exit code.

Test this - 
Open two terminals and connect to your server in the same way: **ssh admin@192.168.246.1; echo $?**
In one of the terminals reboot your server.
Note the exit code.

I bet this is happening to you under nccm and you're noticing the error message.
When you do this from ssh from the shell you won't see the exit code unless you look for it.

BTW, I've improved the exit text upon failure exit - in the new nccm build I pushed.

**Comment by riccalioliojr** [comment]
> Are you rebooting your server inside ssh/nccm or is ssh disconnecting in other ways that 'exit' ?

Nope, not rebooting and I'm only disconnecting either by typing `exit` or pressing `Ctrl+D`, which I believe is basically the same as typing `exit`.

> Or in one command, similar to this: ssh admin@192.168.246.1; echo $?

I'll do this and will let you know if I encounter any non-zero exit codes.

> In one of the terminals reboot your server.

Can't do this anytime soon... I'm connecting to business operations servers.

**Comment by riccalioliojr** [comment]
I got this just now after logging out by pressing `Ctrl+D`:

```sh
user@hostname:~$ logout
Connection to fqdn closed.
2
user@localcomputer:~$
```

**Comment by flyingrhinonz** [comment]
```
user@hostname:~$ logout
Connection to fqdn closed.
2
user@localcomputer:~$
```

That explains it - ssh is exiting with non-zero code. Your shell doesn't care unless you explicitly look for the exit code.
nccm captures non-zero exits and alerts.
Well at least now we know it's not a bug in nccm, neither is it nccm causing ssh any problems.

If possible - fix your syslog and then you'll have logging. Otherwise just set it to critical which disables calls to syslog. Then ignore the exit message displayed on screen.

**Comment by riccalioliojr** [comment]
Please tell me if this is correct because I want to understand it in my own way:

1. `ssh` exits with a non-zero code.
2. `nccm` looks for what happened in the `syslog`
3. `syslog` does not exist, thus the long error message in the OP appears.

Thanks!

**Comment by flyingrhinonz** [comment]
Other way around my friend...

nccm is a wrapper for ssh - 
nccm calls and runs ssh with your settings (from the yml file).
when ssh finishes nccm reads the exit code from ssh.
if ssh exits with any code that is not 0 then nccm writes a syslog message  (and fails in your case with the long debugging message) , and also gives a short message on screen.

**Comment by riccalioliojr** [comment]
I actually understand `nccm`'s concept of being an `ssh` wrapper. What I was clarifying is what exactly is causing `nccm` to crash, which I initially thought is because `nccm` was trying to _read_ the `syslog`. Now I understand `nccm` was actually trying to _write_ to the `syslog`, which does not exist in my case, hence the crash. :-)

Thanks for spending the time looking into this! I'll close the ticket now.
