### ISSUE TITLE
[Feature Request] Return to nccm after ssh session exit

### ISSUE THREAD

**Issue by Justinzobel** [flyingrhinonz/nccm#6]
An option to return to NCCM menu would be great.
Right now I just run it in a loop so as soon as it exits, it starts again as I tend to use the same terminal for SSH sessions all the time.

**Comment by flyingrhinonz** [comment]
Good suggestion.

This could be tricky if the window size changed in between cycles (as nccm uses the initial window size to calculate positioning for everything).
I might need to reinitialize ncurses in between cycles.
Let me think of a solution.

**Comment by flyingrhinonz** [comment]
Feature implemented but as I expected if you resize the window during your ssh session nccm will incorrectly use the original size resulting in a messed up display. 
Working on fixing that next and once I have a good solution I will push a new version.

**Comment by flyingrhinonz** [comment]
Feature ready. It also handles window resize if done outside nccm menu (for example in the ssh session).
I'll test it for a while before pushing.

**Comment by flyingrhinonz** [comment]
Added to local commit. Will push after testing.
